version: '4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    container_name: grafana
  
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    container_name: loki